from transformers_lightning.schedulers.constant_scheduler import ConstantScheduler
from transformers_lightning.schedulers.constant_scheduler_with_warmup import ConstantSchedulerWithWarmup
from transformers_lightning.schedulers.cosine_scheduler_with_warmup import CosineSchedulerWithWarmup
from transformers_lightning.schedulers.cosine_scheduler_with_warmup_and_hard_restart import (
    CosineSchedulerWithWarmupAndHardRestart,
)
from transformers_lightning.schedulers.layerwise_decay_scheduler import PolynomialLayerwiseDecaySchedulerWithWarmup
from transformers_lightning.schedulers.linear_scheduler import LinearScheduler
from transformers_lightning.schedulers.linear_scheduler_with_warmup import LinearSchedulerWithWarmup


schedulers = dict(
    constant=ConstantScheduler,
    constant_warmup=ConstantSchedulerWithWarmup,
    cosine_warmup=CosineSchedulerWithWarmup,
    cosine_warmup_hard_restart=CosineSchedulerWithWarmupAndHardRestart,
    polynomial_layerwise_warmup=PolynomialLayerwiseDecaySchedulerWithWarmup,
    linear=LinearScheduler,
    linear_warmup=LinearSchedulerWithWarmup,
)
